---
  - name: add Jenkins YUM repository
    command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

  - name: add Jenkins rpm key
    command: rpm --import http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key

  - name: install Jenkins
    yum:
      name=jenkins
      state=present

  - name: start Jenkins service
    command: systemctl start jenkins.service

  - name: enable Jenkins service on start-up
    command: systemctl enable jenkins.service

